### ISSUE TITLE
Segnalazione: una riga vuota in più

### ISSUE THREAD

**Issue by aborruso** [IlSole24ORE/QDV2021#1]
Buongiorno,
nel CSV, nell'ultima riga ci sono le doppie virgolette, come se fosse un unico campo e pure vuoto.
La riga vuota è da lasciare, ma senza quelle `""`.

![image](https://user-images.githubusercontent.com/30607/145777522-104a24e3-a94b-4dcf-9250-e1b800e9aa33.png)

Bello vedere anche quest'anno l'aggiornamento dei dati qui

**Comment by IlSole24ORE** [comment]
Grazie mille per il prezioso aiuto! _Dovrei_ aver sistemato anche il problema di codifica caratteri.

(Andrea G.)

**Comment by aborruso** [comment]
Grazie a voi, e grazie per la soluzione del problema encoding caratteri
