### ISSUE TITLE
Segnalazione: FFTC ed FTTH hanno unità di misura incoerenti

### ISSUE THREAD

**Issue by AndreaOmodeo** [IlSole24ORE/QDV2021#2]
L'indicatore FTTC ha come descrizione (unità di misura) "Fibra fino a casa"
FTTH ha come descrizione "fibra fino all'armadietto"

Il significato delle due sigle è l'esatto contrario.

**Comment by IlSole24ORE** [comment]
Esatto, grazie mille per la segnalazione: abbiamo corretto! Le due unità di misura erano invertite per un errore materiale ma i valori sono riferiti alle etichette.

(Andrea G.)
